#!/bin/bash
python scripts/submitSelectModelsToCondor.py --signal MHc-70_MA-15 --background TTLL_powheg
python scripts/submitSelectModelsToCondor.py --signal MHc-70_MA-40 --background TTLL_powheg
python scripts/submitSelectModelsToCondor.py --signal MHc-70_MA-65 --background TTLL_powheg
python scripts/submitSelectModelsToCondor.py --signal MHc-100_MA-15 --background TTLL_powheg
python scripts/submitSelectModelsToCondor.py --signal MHc-100_MA-60 --background TTLL_powheg
python scripts/submitSelectModelsToCondor.py --signal MHc-100_MA-95 --background TTLL_powheg
python scripts/submitSelectModelsToCondor.py --signal MHc-130_MA-15 --background TTLL_powheg
python scripts/submitSelectModelsToCondor.py --signal MHc-130_MA-55 --background TTLL_powheg
python scripts/submitSelectModelsToCondor.py --signal MHc-130_MA-90 --background TTLL_powheg
python scripts/submitSelectModelsToCondor.py --signal MHc-130_MA-125 --background TTLL_powheg
python scripts/submitSelectModelsToCondor.py --signal MHc-160_MA-15 --background TTLL_powheg
python scripts/submitSelectModelsToCondor.py --signal MHc-160_MA-85 --background TTLL_powheg
python scripts/submitSelectModelsToCondor.py --signal MHc-160_MA-120 --background TTLL_powheg
python scripts/submitSelectModelsToCondor.py --signal MHc-160_MA-155 --background TTLL_powheg
python scripts/submitSelectModelsToCondor.py --signal MHc-70_MA-15 --background VV
python scripts/submitSelectModelsToCondor.py --signal MHc-70_MA-40 --background VV
python scripts/submitSelectModelsToCondor.py --signal MHc-70_MA-65 --background VV
python scripts/submitSelectModelsToCondor.py --signal MHc-100_MA-15 --background VV
python scripts/submitSelectModelsToCondor.py --signal MHc-100_MA-60 --background VV
python scripts/submitSelectModelsToCondor.py --signal MHc-100_MA-95 --background VV
python scripts/submitSelectModelsToCondor.py --signal MHc-130_MA-15 --background VV
python scripts/submitSelectModelsToCondor.py --signal MHc-130_MA-55 --background VV
python scripts/submitSelectModelsToCondor.py --signal MHc-130_MA-90 --background VV
python scripts/submitSelectModelsToCondor.py --signal MHc-130_MA-125 --background VV
python scripts/submitSelectModelsToCondor.py --signal MHc-160_MA-15 --background VV
python scripts/submitSelectModelsToCondor.py --signal MHc-160_MA-85 --background VV
python scripts/submitSelectModelsToCondor.py --signal MHc-160_MA-120 --background VV
python scripts/submitSelectModelsToCondor.py --signal MHc-160_MA-155 --background VV
