#!/bin/sh
RUN=$1
ERA=$2
CHANNEL=$3
NETWORK=$4

./run${RUN}.sh $ERA $CHANNEL $NETWORK MHc-70_MA-65
./run${RUN}.sh $ERA $CHANNEL $NETWORK MHc-100_MA-95
./run${RUN}.sh $ERA $CHANNEL $NETWORK MHc-130_MA-90
./run${RUN}.sh $ERA $CHANNEL $NETWORK MHc-160_MA-85
./run${RUN}.sh $ERA $CHANNEL $NETWORK MHc-160_MA-120
