hist_configs = {
    # muons
    "muons/1/pt": {"x_title": "p_{T}(#mu1) [GeV]",
                   "y_title": "Events / 5 GeV",
                   "x_range": [0., 250.],
                   "rebin": 5},
    "muons/1/eta": {"x_title": "#eta(#mu1)",
                    "y_title": "Events",
                    "x_range": [-2.4, 2.4],
                    "rebin": 5},
    "muons/1/phi": {"x_title": "#phi(#mu1)",
                    "y_title": "Events",
                    "x_range": [-3.2, 3.2],
                    "rebin": 4},
    "muons/2/pt": {"x_title": "p_{T}(#mu2) [GeV]",
                   "y_title": "Events / 5 GeV",
                   "x_range": [0., 200.],
                   "rebin": 5},
    "muons/2/eta": {"x_title": "#eta(#mu2)",
                    "y_title": "Events",
                    "x_range": [-2.4, 2.4],
                    "rebin": 5},
    "muons/2/phi": {"x_title": "#phi(#mu2)",
                    "y_title": "Events",
                    "x_range": [-3.2, 3.2],
                    "rebin": 4},
    "muons/3/pt": {"x_title": "p_{T}(#mu3) [GeV]",
                   "y_title": "Events / 5 GeV",
                   "x_range": [0., 150.],
                   "rebin": 5},
    "muons/3/eta": {"x_title": "#eta(#mu3)",
                    "y_title": "Events",
                    "x_range": [-2.4, 2.4],
                    "rebin": 5},
    "muons/3/phi": {"x_title": "#phi(#mu3)",
                    "y_title": "Events",
                    "x_range": [-3.2, 3.2],
                    "rebin": 4}, 
    # jets
    "jets/1/pt": {"x_title": "p_{T}(j1) [GeV]",
                  "y_title": "Events / 10 GeV",
                  "x_range": [0., 300.],
                  "rebin": 10
                  },
    "jets/1/eta": {"x_title": "#eta(j1)",
                   "y_title": "Events",
                   "x_range": [-2.4, 2.4],
                   "rebin": 5
                   },
    "jets/1/phi": {"x_title": "#phi(j1)",
                   "y_title": "Events",
                   "x_range": [-3.2, 3.2],
                   "rebin": 4
                   },
    "jets/1/mass": {"x_title": "M(j1)",
                    "y_title": "Events / GeV",
                    "x_range": [0., 50.],
                    },
    "jets/2/pt": {"x_title": "p_{T}(j2) [GeV]",
                  "y_title": "Events / 10 GeV",
                  "x_range": [0., 250.],
                  "rebin": 10
                  },
    "jets/2/eta": {"x_title": "#eta(j2)",
                   "y_title": "Events",
                   "x_range": [-2.4, 2.4],
                   "rebin": 5
                   },
    "jets/2/phi": {"x_title": "#phi(j2)",
                   "y_title": "Events",
                   "x_range": [-3.2, 3.2],
                   "rebin": 4
                   },
    "jets/2/mass": {"x_title": "M(j2)",
                    "y_title": "Events / GeV",
                    "x_range": [0., 50.],
                    },
    "jets/3/pt": {"x_title": "p_{T}(j3) [GeV]",
                  "y_title": "Events / 10 GeV",
                  "x_range": [0., 200.],
                  "rebin": 10
                  },
    "jets/3/eta": {"x_title": "#eta(j3)",
                   "y_title": "Events",
                   "x_range": [-2.4, 2.4],
                   "rebin": 5
                   },
    "jets/3/phi": {"x_title": "#phi(j3)",
                   "y_title": "Events",
                   "x_range": [-3.2, 3.2],
                   "rebin": 4
                   },
    "jets/3/mass": {"x_title": "M(j3)",
                    "y_title": "Events / GeV",
                    "x_range": [0., 50.],
                    },
    "jets/4/pt": {"x_title": "p_{T}(j4) [GeV]",
                  "y_title": "Events / 10 GeV",
                  "x_range": [0., 200.],
                  "rebin": 10
                  },
    "jets/4/eta": {"x_title": "#eta(j4)",
                   "y_title": "Events",
                   "x_range": [-2.4, 2.4],
                   "rebin": 5
                   },
    "jets/4/phi": {"x_title": "#phi(j4)",
                   "y_title": "Events",
                   "x_range": [-3.2, 3.2],
                   "rebin": 4
                   },
    "jets/4/mass": {"x_title": "M(j4)",
                    "y_title": "Events / GeV",
                    "x_range": [0., 50.],
                    },
    "jets/size": {"x_title": "N_{j}",
                  "y_title": "Events",
                  "x_range": [0., 10.]
                  },
    "jets/HT": {"x_title": "H_{T} [GeV]",
                "y_title": "Events / 10 GeV",
                "x_range": [0., 1000.],
                "rebin": 10
                },
    # ZCand
    "ZCand/pt": {"x_title": "p_{T}(Z) [GeV]",
                 "y_title": "Events / 5 GeV",
                 "x_range": [0., 200.],
                 "rebin": 5
                 },
    "ZCand/eta": {"x_title": "#eta(Z)",
                  "y_title": "Events",
                  "x_range": [-5., 5.],
                  "rebin": 10
                  },
    "ZCand/phi": {"x_title": "#phi(Z)",
                  "y_title": "Events",
                  "x_range": [-3.2, 3.2],
                  "rebin": 8
                  },
    "ZCand/mass": {"x_title": "M(Z) [GeV]",
                   "y_title": "Events / 2 GeV",
                   "x_range": [75., 105.],
                   "rebin": 2
                   },
    "xZCand/pt": {"x_title": "p_{T}(xZ) [GeV]",
                 "y_title": "Events / 5 GeV",
                 "x_range": [0., 200.],
                 "rebin": 5
                 },
    "xZCand/eta": {"x_title": "#eta(xZ)",
                  "y_title": "Events",
                  "x_range": [-5., 5.],
                  "rebin": 10
                  },
    "xZCand/phi": {"x_title": "#phi(xZ)",
                  "y_title": "Events",
                  "x_range": [-3.2, 3.2],
                  "rebin": 8
                  },
    "xZCand/mass": {"x_title": "M(xZ) [GeV]",
                   "y_title": "Events / 5 GeV",
                   "x_range": [0., 300.],
                   "rebin": 5
                   },
    # scores
    "MHc-70_MA-150vsTTLL_powheg/score": {"x_title": "score",
                                  "y_title": "Events",
                                  "x_range": [0., 1.],
                                  "logY": True,
                                  "rebin": 50
                                  },
    "MHc-70_MA-40vsTTLL_powheg/score": {"x_title": "score",
                                  "y_title": "Events",
                                  "x_range": [0., 1.],
                                  "logY": True,
                                  "rebin": 50
                                  },
    "MHc-70_MA-650vsTTLL_powheg/score": {"x_title": "score",
                                  "y_title": "Events",
                                  "x_range": [0., 1.],
                                  "logY": True,
                                  "rebin": 50
                                  },
    "MHc-100_MA-150vsTTLL_powheg/score": {"x_title": "score",
                                  "y_title": "Events",
                                  "x_range": [0., 1.],
                                  "logY": True,
                                  "rebin": 50
                                  },
    "MHc-100_MA-60vsTTLL_powheg/score": {"x_title": "score",
                                  "y_title": "Events",
                                  "x_range": [0., 1.],
                                  "logY": True,
                                  "rebin": 50
                                  },
    "MHc-100_MA-950vsTTLL_powheg/score": {"x_title": "score",
                                  "y_title": "Events",
                                  "x_range": [0., 1.],
                                  "logY": True,
                                  "rebin": 50
                                  },
    "MHc-130_MA-150vsTTLL_powheg/score": {"x_title": "score",
                                  "y_title": "Events",
                                  "x_range": [0., 1.],
                                  "logY": True,
                                  "rebin": 50
                                  },
    "MHc-130_MA-5050vsTTLL_powheg/score": {"x_title": "score",
                                  "y_title": "Events",
                                  "x_range": [0., 1.],
                                  "logY": True,
                                  "rebin": 50
                                  },
    "MHc-130_MA-90vsTTLL_powheg/score": {"x_title": "score",
                                  "y_title": "Events",
                                  "x_range": [0., 1.],
                                  "logY": True,
                                  "rebin": 50
                                  },
    "MHc-130_MA-1250vsTTLL_powheg/score": {"x_title": "score",
                                  "y_title": "Events",
                                  "x_range": [0., 1.],
                                  "logY": True,
                                  "rebin": 50
                                  },
    "MHc-160_MA-150vsTTLL_powheg/score": {"x_title": "score",
                                  "y_title": "Events",
                                  "x_range": [0., 1.],
                                  "logY": True,
                                  "rebin": 50
                                  },
    "MHc-160_MA-850vsTTLL_powheg/score": {"x_title": "score",
                                  "y_title": "Events",
                                  "x_range": [0., 1.],
                                  "logY": True,
                                  "rebin": 50
                                  },
    "MHc-160_MA-120vsTTLL_powheg/score": {"x_title": "score",
                                  "y_title": "Events",
                                  "x_range": [0., 1.],
                                  "logY": True,
                                  "rebin": 50
                                  },
    "MHc-160_MA-15050vsTTLL_powheg/score": {"x_title": "score",
                                  "y_title": "Events",
                                  "x_range": [0., 1.],
                                  "logY": True,
                                  "rebin": 50
                                  },
    "MHc-70_MA-150vsVV/score": {"x_title": "score",
                                  "y_title": "Events",
                                  "x_range": [0., 1.],
                                  "logY": True,
                                  "rebin": 50
                                  },
    "MHc-70_MA-40vsVV/score": {"x_title": "score",
                                  "y_title": "Events",
                                  "x_range": [0., 1.],
                                  "logY": True,
                                  "rebin": 50
                                  },
    "MHc-70_MA-650vsVV/score": {"x_title": "score",
                                  "y_title": "Events",
                                  "x_range": [0., 1.],
                                  "logY": True,
                                  "rebin": 50
                                  },
    "MHc-100_MA-150vsVV/score": {"x_title": "score",
                                  "y_title": "Events",
                                  "x_range": [0., 1.],
                                  "logY": True,
                                  "rebin": 50
                                  },
    "MHc-100_MA-60vsVV/score": {"x_title": "score",
                                  "y_title": "Events",
                                  "x_range": [0., 1.],
                                  "logY": True,
                                  "rebin": 50
                                  },
    "MHc-100_MA-950vsVV/score": {"x_title": "score",
                                  "y_title": "Events",
                                  "x_range": [0., 1.],
                                  "logY": True,
                                  "rebin": 50
                                  },
    "MHc-130_MA-150vsVV/score": {"x_title": "score",
                                  "y_title": "Events",
                                  "x_range": [0., 1.],
                                  "logY": True,
                                  "rebin": 50
                                  },
    "MHc-130_MA-5050vsVV/score": {"x_title": "score",
                                  "y_title": "Events",
                                  "x_range": [0., 1.],
                                  "logY": True,
                                  "rebin": 50
                                  },
    "MHc-130_MA-90vsVV/score": {"x_title": "score",
                                  "y_title": "Events",
                                  "x_range": [0., 1.],
                                  "logY": True,
                                  "rebin": 50
                                  },
    "MHc-130_MA-1250vsVV/score": {"x_title": "score",
                                  "y_title": "Events",
                                  "x_range": [0., 1.],
                                  "logY": True,
                                  "rebin": 50
                                  },
    "MHc-160_MA-150vsVV/score": {"x_title": "score",
                                  "y_title": "Events",
                                  "x_range": [0., 1.],
                                  "logY": True,
                                  "rebin": 50
                                  },
    "MHc-160_MA-850vsVV/score": {"x_title": "score",
                                  "y_title": "Events",
                                  "x_range": [0., 1.],
                                  "logY": True,
                                  "rebin": 50
                                  },
    "MHc-160_MA-120vsVV/score": {"x_title": "score",
                                  "y_title": "Events",
                                  "x_range": [0., 1.],
                                  "logY": True,
                                  "rebin": 50
                                  },
    "MHc-160_MA-15050vsVV/score": {"x_title": "score",
                                  "y_title": "Events",
                                  "x_range": [0., 1.],
                                  "logY": True,
                                  "rebin": 50
                                  },
}
