histConfigs = {"muons/1/pt": {"xTitle": "p_{T}(#mu1)",
                         "yTitle": "Events / 10 GeV",
                         "xRange": [0., 300.],
                         "rebin": 10,
                         "logy": False},
          "muons/2/pt": {"xTitle": "p_{T}(#mu2)",
                         "yTitle": "Events / 10 GeV",
                         "xRange": [0., 200.],
                         "rebin": 10,
                         "logy": False},
          "muons/3/pt": {"xTitle": "p_{T}(#mu3)",
                         "yTitle": "Events / 10 GeV",
                         "xRange": [0., 300.],
                         "rebin": 10,
                         "logy": False},
          "muons/1/eta": {"xTitle": "#eta(#mu1)",
                          "yTitle": "Events",
                          "xRange": [-2.4, 2.4],
                          #"rebin": 10,
                          "logy": False},
          "muons/2/eta": {"xTitle": "#eta(#mu2)",
                          "yTitle": "Events",
                          "xRange": [-2.4, 2.4],
                          #"rebin": 10,
                          "logy": False},
          "muons/3/eta": {"xTitle": "#eta(#mu3)",
                          "yTitle": "Events",
                          "xRange": [-2.4, 2.4],
                          #"rebin": 10,
                          "logy": False},
          "muons/1/phi": {"xTitle": "#phi(#mu1)",
                          "yTitle": "Events",
                          "xRange": [-3.2, 3.2],
                          #"rebin": 10,
                          "logy": False},
          "muons/2/phi": {"xTitle": "#phi(#mu2)",
                          "yTitle": "Events",
                          "xRange": [-3.2, 3.2],
                          #"rebin": 10,
                          "logy": False},
          "muons/3/phi": {"xTitle": "#phi(#mu3)",
                          "yTitle": "Events",
                          "xRange": [-3.2, 3.2],
                          #"rebin": 10,
                          "logy": False},
          "electrons/1/pt": {"xTitle": "p_{T}(e)",
                             "yTitle": "Events / 10 GeV",
                             "xRange": [0., 300.],
                             "rebin": 10,
                             "logy": False},
          "electrons/1/eta": {"xTitle": "#eta(e)",
                              "yTitle": "Events",
                              "xRange": [-2.5, 2.5],
                              #"rebin": 10,
                              "logy": False},
          "electrons/1/Phi": {"xTitle": "#phi(e)",
                              "yTitle": "Events",
                              "xRange": [-3.2, 3.2],
                              #"rebin": 10,
                              "logy": False},
          "jets/1/pt": {"xTitle": "p_{T}(j1)",
                        "yTitle": "Events / 10 GeV",
                        "xRange": [0., 300.],
                        "rebin": 10,
                        "logy": False},
          "jets/2/pt": {"xTitle": "p_{T}(j2)",
                        "yTitle": "Events / 10 GeV",
                        "xRange": [0., 300.],
                        "rebin": 10,
                        "logy": False},
          "jets/3/pt": {"xTitle": "p_{T}(j3)",
                        "yTitle": "Events / 10 GeV",
                        "xRange": [0., 300.],
                        "rebin": 10,
                        "logy": False},
          "jets/4/pt": {"xTitle": "p_{T}(j4)",
                        "yTitle": "Events / 10 GeV",
                        "xRange": [0., 300.],
                        "rebin": 10,
                        "logy": False},
          "jets/5/pt": {"xTitle": "p_{T}(j5)",
                        "yTitle": "Events / 10 GeV",
                        "xRange": [0., 300.],
                        "rebin": 10,
                        "logy": False},
          "jets/1/eta": {"xTitle": "#eta(j1)",
                         "yTitle": "Events",
                         "xRange": [-2.4, 2.4],
                         #"rebin": 10,
                         "logy": False},
          "jets/2/eta": {"xTitle": "#eta(j2)",
                         "yTitle": "Events",
                         "xRange": [-2.4, 2.4],
                         #"rebin": 10,
                         "logy": False},
          "jets/3/eta": {"xTitle": "#eta(j3)",
                         "yTitle": "Events",
                         "xRange": [-2.4, 2.4],
                         #"rebin": 10,
                         "logy": False},
          "jets/4/eta": {"xTitle": "#eta(j4)",
                         "yTitle": "Events",
                         "xRange": [-2.4, 2.4],
                         #"rebin": 10,
                         "logy": False},
          "jets/5/eta": {"xTitle": "#eta(j5)",
                         "yTitle": "Events",
                         "xRange": [-2.4, 2.4],
                         #"rebin": 10,
                         "logy": False},
          "jets/1/phi": {"xTitle": "#phi(j1)",
                         "yTitle": "Events",
                         "xRange": [-3.2, 3.2],
                         #"rebin": 10,
                         "logy": False},
          "jets/2/phi": {"xTitle": "#phi(j2)",
                         "yTitle": "Events",
                         "xRange": [-3.2, 3.2],
                         #"rebin": 10,
                         "logy": False},
          "jets/3/phi": {"xTitle": "#phi(j3)",
                         "yTitle": "Events",
                         "xRange": [-3.2, 3.2],
                         #"rebin": 10,
                         "logy": False},
          "jets/4/phi": {"xTitle": "#phi(j4)",
                         "yTitle": "Events",
                         "xRange": [-3.2, 3.2],
                         #"rebin": 10,
                         "logy": False},
          "jets/5/phi": {"xTitle": "#phi(j5)",
                         "yTitle": "Events",
                         "xRange": [-3.2, 3.2],
                         #"rebin": 10,
                         "logy": False},
          "jets/1/mass": {"xTitle": "M(j1)",
                          "yTitle": "Events / 10 GeV",
                          "xRange": [0., 300.],
                          "rebin": 10,
                          "logy": False},
          "jets/2/mass": {"xTitle": "M(j2)",
                          "yTitle": "Events / 10 GeV",
                          "xRange": [0., 300.],
                          "rebin": 10,
                          "logy": False},
          "jets/3/mass": {"xTitle": "M(j3)",
                          "yTitle": "Events / 10 GeV",
                          "xRange": [0., 300.],
                          "rebin": 10,
                          "logy": False},
          "jets/4/mass": {"xTitle": "M(j4)",
                          "yTitle": "Events / 10 GeV",
                          "xRange": [0., 300.],
                          "rebin": 10,
                          "logy": False},
          "jets/5/mass": {"xTitle": "M(j5)",
                          "yTitle": "Events / 10 GeV",
                          "xRange": [0., 300.],
                          "rebin": 10,
                          "logy": False}, 
          "jets/1/charge": {"xTitle": "charge(j1)",
                            "yTitle": "Events",
                            "xRange": [-1., 1.],
                            #"rebin": 10, 
                            "logy": False},
          "jets/2/charge": {"xTitle": "charge(j2)",
                            "yTitle": "Events",
                            "xRange": [-1., 1.],
                            #"rebin": 10, 
                            "logy": False},
          "jets/3/charge": {"xTitle": "charge(j3)",
                            "yTitle": "Events",
                            "xRange": [-1., 1.],
                            #"rebin": 10, 
                            "logy": False},
          "jets/4/charge": {"xTitle": "charge(j4)",
                            "yTitle": "Events",
                            "xRange": [-1., 1.],
                            #"rebin": 10, 
                            "logy": False},
          "jets/5/charge": {"xTitle": "charge(j5)",
                            "yTitle": "Events",
                            "xRange": [-1., 1.],
                            #"rebin": 10, 
                            "logy": False},
          "jets/size": {"xTitle": "N_{j}",
                        "yTitle": "Events",
                        "xRange": [0, 10],
                        "logy": False},
          "bjets/1/pt": {"xTitle": "p_{T}(b1)",
                         "yTitle": "Events / 10 GeV",
                         "xRange": [0., 300.],
                         "rebin": 10,
                         "logy": False},
          "bjets/2/pt": {"xTitle": "p_{T}(b2)",
                         "yTitle": "Events / 10 GeV",
                         "xRange": [0., 300.],
                         "rebin": 10,
                         "logy": False},
          "bjets/3/pt": {"xTitle": "p_{T}(b3)",
                         "yTitle": "Events / 10 GeV",
                         "xRange": [0., 300.],
                         "rebin": 10,
                         "logy": False},
          "bjets/1/eta": {"xTitle": "#eta(b1)",
                         "yTitle": "Events",
                         "xRange": [-2.4, 2.4],
                         #"rebin": 10,
                         "logy": False},
          "bjets/2/eta": {"xTitle": "#eta(b2)",
                         "yTitle": "Events",
                         "xRange": [-2.4, 2.4],
                         #"rebin": 10,
                         "logy": False},
          "bjets/3/eta": {"xTitle": "#eta(b3)",
                         "yTitle": "Events",
                         "xRange": [-2.4, 2.4],
                         #"rebin": 10,
                         "logy": False},
          "bjets/1/phi": {"xTitle": "#phi(b1)",
                         "yTitle": "Events",
                         "xRange": [-3.2, 3.2],
                         #"rebin": 10,
                         "logy": False},
          "bjets/2/phi": {"xTitle": "#phi(b2)",
                         "yTitle": "Events",
                         "xRange": [-3.2, 3.2],
                         #"rebin": 10,
                         "logy": False},
          "bjets/3/phi": {"xTitle": "#phi(b3)",
                         "yTitle": "Events",
                         "xRange": [-3.2, 3.2],
                         #"rebin": 10,
                         "logy": False},
          "bjets/1/mass": {"xTitle": "M(b1)",
                           "yTitle": "Events / 10 GeV",
                           "xRange": [0., 300.],
                           "rebin": 10,
                           "logy": False},
          "bjets/2/mass": {"xTitle": "M(b2)",
                           "yTitle": "Events / 10 GeV",
                           "xRange": [0., 300.],
                           "rebin": 10,
                           "logy": False},
          "bjets/3/mass": {"xTitle": "M(b3)",
                           "yTitle": "Events / 10 GeV",
                           "xRange": [0., 300.],
                           "rebin": 10,
                           "logy": False},
          "bjets/1/charge": {"xTitle": "charge(b1)",
                             "yTitle": "Events",
                             "xRange": [-1., 1.],
                             #"rebin": 10, 
                             "logy": False},
          "bjets/2/charge": {"xTitle": "charge(b2)",
                             "yTitle": "Events",
                             "xRange": [-1., 1.],
                             #"rebin": 10, 
                             "logy": False},
          "bjets/3/charge": {"xTitle": "charge(b3)",
                             "yTitle": "Events",
                             "xRange": [-1., 1.],
                             #"rebin": 10, 
                             "logy": False},
          "bjets/size": {"xTitle": "N_{b}",
                         "yTitle": "Events",
                         "xRange": [0, 10],
                         "logy": False},
          "METv/pt": {"xTitle": "E_{T}^{miss}",
                      "yTitle": "Events / 10 GeV",
                      "xRange": [0., 300.],
                      "rebin": 10,
                      "logy": False},
          "METv/phi": {"xTitle": "#phi(#vec{p_{T}}^{miss}})",
                       "yTitle": "Events",
                       "xRange": [-3.2, 3.2],
                       #"rebin": 10,
                       "logy": False},
          "ZCand/mass": {"xTitle": "M(Z)",
                       "yTitle": "Events / GeV",
                       "xRange": [75, 105],
                       "logy": False},
          "ZCand/eta": {"xTitle": "#eta(Z)",
                        "yTitle": "Events",
                        "xRange": [-5., 5.],
                        "rebin": 5,
                        "logy": False},
          "MHc-70_MA-15/ACand/pt": {"xTitle": "p_{T}(A)",
                                    "yTitle": "Events / GeV",
                                    "xRange": [0., 200.],
                                    #"rebin": 5,
                                    "logy": False},
          "MHc-70_MA-15/ACand/eta": {"xTitle": "#eta(A)",
                                     "yTitle": "Events",
                                     "xRange": [-5., 5.],
                                     #"rebin": 5,
                                     "logy": False},
          "MHc-70_MA-15/ACand/phi": {"xTitle": "#phi(A)",
                                     "yTitle": "Events",
                                     "xRange": [-3.2, 3.2],
                                     #"rebin": 5,
                                     "logy": False},
          "MHc-70_MA-15/ACand/mass": {"xTitle": "M(A)",
                                     "yTitle": "Events / GeV",
                                     "xRange": [0., 200.],
                                     #"rebin": 5,
                                     "logy": False},
          "MHc-70_MA-15/score_TTFake": {"xTitle": "score(vsfake)",
                                              "yTitle": "Events",
                                              "xRange": [0., 1.],
                                              "rebin": 2,
                                              "logy": False},
          "MHc-70_MA-15/score_TTX": {"xTitle": "score(vsTTX)",
                                           "yTitle": "Events",
                                           "xRange": [0., 1.],
                                           "rebin": 2,
                                           "logy": False},
          "MHc-70_MA-40/ACand/pt": {"xTitle": "p_{T}(A)",
                                    "yTitle": "Events / GeV",
                                    "xRange": [0., 200.],
                                    #"rebin": 5,
                                    "logy": False},
          "MHc-70_MA-40/ACand/eta": {"xTitle": "#eta(A)",
                                     "yTitle": "Events",
                                     "xRange": [-5., 5.],
                                     #"rebin": 5,
                                     "logy": False},
          "MHc-70_MA-40/ACand/phi": {"xTitle": "#phi(A)",
                                     "yTitle": "Events",
                                     "xRange": [-3.2, 3.2],
                                     #"rebin": 5,
                                     "logy": False},
          "MHc-70_MA-40/ACand/mass": {"xTitle": "M(A)",
                                     "yTitle": "Events / GeV",
                                     "xRange": [0., 200.],
                                     #"rebin": 5,
                                     "logy": False},
          "MHc-70_MA-40/score_TTFake": {"xTitle": "score(vsfake)",
                                              "yTitle": "Events",
                                              "xRange": [0., 1.],
                                              "rebin": 2,
                                              "logy": False},
          "MHc-70_MA-40/score_TTX": {"xTitle": "score(vsTTX)",
                                           "yTitle": "Events",
                                           "xRange": [0., 1.],
                                           "rebin": 2,
                                           "logy": False},
          "MHc-70_MA-65/ACand/pt": {"xTitle": "p_{T}(A)",
                                    "yTitle": "Events / GeV",
                                    "xRange": [0., 200.],
                                    #"rebin": 5,
                                    "logy": False},
          "MHc-70_MA-65/ACand/eta": {"xTitle": "#eta(A)",
                                     "yTitle": "Events",
                                     "xRange": [-5., 5.],
                                     #"rebin": 5,
                                     "logy": False},
          "MHc-70_MA-65/ACand/phi": {"xTitle": "#phi(A)",
                                     "yTitle": "Events",
                                     "xRange": [-3.2, 3.2],
                                     #"rebin": 5,
                                     "logy": False},
          "MHc-70_MA-65/ACand/mass": {"xTitle": "M(A)",
                                     "yTitle": "Events / GeV",
                                     "xRange": [0., 200.],
                                     #"rebin": 5,
                                     "logy": False},
          "MHc-70_MA-65/score_TTFake": {"xTitle": "score(vsfake)",
                                              "yTitle": "Events",
                                              "xRange": [0., 1.],
                                              "rebin": 2,
                                              "logy": False},
          "MHc-70_MA-65/score_TTX": {"xTitle": "score(vsTTX)",
                                           "yTitle": "Events",
                                           "xRange": [0., 1.],
                                           "rebin": 2,
                                           "logy": False},
          "MHc-100_MA-15/ACand/pt": {"xTitle": "p_{T}(A)",
                                    "yTitle": "Events / GeV",
                                    "xRange": [0., 200.],
                                    #"rebin": 5,
                                    "logy": False},
          "MHc-100_MA-15/ACand/eta": {"xTitle": "#eta(A)",
                                     "yTitle": "Events",
                                     "xRange": [-5., 5.],
                                     #"rebin": 5,
                                     "logy": False},
          "MHc-100_MA-15/ACand/phi": {"xTitle": "#phi(A)",
                                     "yTitle": "Events",
                                     "xRange": [-3.2, 3.2],
                                     #"rebin": 5,
                                     "logy": False},
          "MHc-100_MA-15/ACand/mass": {"xTitle": "M(A)",
                                     "yTitle": "Events / GeV",
                                     "xRange": [0., 200.],
                                     #"rebin": 5,
                                     "logy": False},
          "MHc-100_MA-15/score_TTFake": {"xTitle": "score(vsfake)",
                                              "yTitle": "Events",
                                              "xRange": [0., 1.],
                                              "rebin": 2,
                                              "logy": False},
          "MHc-100_MA-15/score_TTX": {"xTitle": "score(vsTTX)",
                                           "yTitle": "Events",
                                           "xRange": [0., 1.],
                                           "rebin": 2,
                                           "logy": False},
          "MHc-100_MA-60/ACand/pt": {"xTitle": "p_{T}(A)",
                                    "yTitle": "Events / GeV",
                                    "xRange": [0., 200.],
                                    #"rebin": 5,
                                    "logy": False},
          "MHc-100_MA-60/ACand/eta": {"xTitle": "#eta(A)",
                                     "yTitle": "Events",
                                     "xRange": [-5., 5.],
                                     #"rebin": 5,
                                     "logy": False},
          "MHc-100_MA-60/ACand/phi": {"xTitle": "#phi(A)",
                                     "yTitle": "Events",
                                     "xRange": [-3.2, 3.2],
                                     #"rebin": 5,
                                     "logy": False},
          "MHc-100_MA-60/ACand/mass": {"xTitle": "M(A)",
                                     "yTitle": "Events / GeV",
                                     "xRange": [0., 200.],
                                     #"rebin": 5,
                                     "logy": False},
          "MHc-100_MA-60/score_TTFake": {"xTitle": "score(vsfake)",
                                              "yTitle": "Events",
                                              "xRange": [0., 1.],
                                              "rebin": 2,
                                              "logy": False},
          "MHc-100_MA-60/score_TTX": {"xTitle": "score(vsTTX)",
                                           "yTitle": "Events",
                                           "xRange": [0., 1.],
                                           "rebin": 2,
                                           "logy": False},
          "MHc-100_MA-95/ACand/pt": {"xTitle": "p_{T}(A)",
                                    "yTitle": "Events / GeV",
                                    "xRange": [0., 200.],
                                    #"rebin": 5,
                                    "logy": False},
          "MHc-100_MA-95/ACand/eta": {"xTitle": "#eta(A)",
                                     "yTitle": "Events",
                                     "xRange": [-5., 5.],
                                     #"rebin": 5,
                                     "logy": False},
          "MHc-100_MA-95/ACand/phi": {"xTitle": "#phi(A)",
                                     "yTitle": "Events",
                                     "xRange": [-3.2, 3.2],
                                     #"rebin": 5,
                                     "logy": False},
          "MHc-100_MA-95/ACand/mass": {"xTitle": "M(A)",
                                     "yTitle": "Events / GeV",
                                     "xRange": [0., 200.],
                                     #"rebin": 5,
                                     "logy": False},
          "MHc-100_MA-95/score_TTFake": {"xTitle": "score(vsfake)",
                                              "yTitle": "Events",
                                              "xRange": [0., 1.],
                                              "rebin": 2,
                                              "logy": False},
          "MHc-100_MA-95/score_TTX": {"xTitle": "score(vsTTX)",
                                           "yTitle": "Events",
                                           "xRange": [0., 1.],
                                           "rebin": 2,
                                           "logy": False},
          "MHc-130_MA-15/ACand/pt": {"xTitle": "p_{T}(A)",
                                    "yTitle": "Events / GeV",
                                    "xRange": [0., 200.],
                                    #"rebin": 5,
                                    "logy": False},
          "MHc-130_MA-15/ACand/eta": {"xTitle": "#eta(A)",
                                     "yTitle": "Events",
                                     "xRange": [-5., 5.],
                                     #"rebin": 5,
                                     "logy": False},
          "MHc-130_MA-15/ACand/phi": {"xTitle": "#phi(A)",
                                     "yTitle": "Events",
                                     "xRange": [-3.2, 3.2],
                                     #"rebin": 5,
                                     "logy": False},
          "MHc-130_MA-15/ACand/mass": {"xTitle": "M(A)",
                                     "yTitle": "Events / GeV",
                                     "xRange": [0., 200.],
                                     #"rebin": 5,
                                     "logy": False},
          "MHc-130_MA-15/score_TTFake": {"xTitle": "score(vsfake)",
                                              "yTitle": "Events",
                                              "xRange": [0., 1.],
                                              "rebin": 2,
                                              "logy": False},
          "MHc-130_MA-15/score_TTX": {"xTitle": "score(vsTTX)",
                                           "yTitle": "Events",
                                           "xRange": [0., 1.],
                                           "rebin": 2,
                                           "logy": False},
          "MHc-130_MA-55/ACand/pt": {"xTitle": "p_{T}(A)",
                                    "yTitle": "Events / GeV",
                                    "xRange": [0., 200.],
                                    #"rebin": 5,
                                    "logy": False},
          "MHc-130_MA-55/ACand/eta": {"xTitle": "#eta(A)",
                                     "yTitle": "Events",
                                     "xRange": [-5., 5.],
                                     #"rebin": 5,
                                     "logy": False},
          "MHc-130_MA-55/ACand/phi": {"xTitle": "#phi(A)",
                                     "yTitle": "Events",
                                     "xRange": [-3.2, 3.2],
                                     #"rebin": 5,
                                     "logy": False},
          "MHc-130_MA-55/ACand/mass": {"xTitle": "M(A)",
                                     "yTitle": "Events / GeV",
                                     "xRange": [0., 200.],
                                     #"rebin": 5,
                                     "logy": False},
          "MHc-130_MA-55/score_TTFake": {"xTitle": "score(vsfake)",
                                              "yTitle": "Events",
                                              "xRange": [0., 1.],
                                              "rebin": 2,
                                              "logy": False},
          "MHc-130_MA-55/score_TTX": {"xTitle": "score(vsTTX)",
                                           "yTitle": "Events",
                                           "xRange": [0., 1.],
                                           "rebin": 2,
                                           "logy": False},
          "MHc-130_MA-90/ACand/pt": {"xTitle": "p_{T}(A)",
                                    "yTitle": "Events / GeV",
                                    "xRange": [0., 200.],
                                    #"rebin": 5,
                                    "logy": False},
          "MHc-130_MA-90/ACand/eta": {"xTitle": "#eta(A)",
                                     "yTitle": "Events",
                                     "xRange": [-5., 5.],
                                     #"rebin": 5,
                                     "logy": False},
          "MHc-130_MA-90/ACand/phi": {"xTitle": "#phi(A)",
                                     "yTitle": "Events",
                                     "xRange": [-3.2, 3.2],
                                     #"rebin": 5,
                                     "logy": False},
          "MHc-130_MA-90/ACand/mass": {"xTitle": "M(A)",
                                     "yTitle": "Events / GeV",
                                     "xRange": [0., 200.],
                                     #"rebin": 5,
                                     "logy": False},
          "MHc-130_MA-90/score_TTFake": {"xTitle": "score(vsfake)",
                                              "yTitle": "Events",
                                              "xRange": [0., 1.],
                                              "rebin": 2,
                                              "logy": False},
          "MHc-130_MA-90/score_TTX": {"xTitle": "score(vsTTX)",
                                           "yTitle": "Events",
                                           "xRange": [0., 1.],
                                           "rebin": 2,
                                           "logy": False},
          "MHc-130_MA-125/ACand/pt": {"xTitle": "p_{T}(A)",
                                    "yTitle": "Events / GeV",
                                    "xRange": [0., 200.],
                                    #"rebin": 5,
                                    "logy": False},
          "MHc-130_MA-125/ACand/eta": {"xTitle": "#eta(A)",
                                     "yTitle": "Events",
                                     "xRange": [-5., 5.],
                                     #"rebin": 5,
                                     "logy": False},
          "MHc-130_MA-125/ACand/phi": {"xTitle": "#phi(A)",
                                     "yTitle": "Events",
                                     "xRange": [-3.2, 3.2],
                                     #"rebin": 5,
                                     "logy": False},
          "MHc-130_MA-125/ACand/mass": {"xTitle": "M(A)",
                                     "yTitle": "Events / GeV",
                                     "xRange": [0., 200.],
                                     #"rebin": 5,
                                     "logy": False},
          "MHc-130_MA-125/score_TTFake": {"xTitle": "score(vsfake)",
                                              "yTitle": "Events",
                                              "xRange": [0., 1.],
                                              "rebin": 2,
                                              "logy": False},
          "MHc-130_MA-125/score_TTX": {"xTitle": "score(vsTTX)",
                                           "yTitle": "Events",
                                           "xRange": [0., 1.],
                                           "rebin": 2,
                                           "logy": False},
          "MHc-160_MA-15/ACand/pt": {"xTitle": "p_{T}(A)",
                                    "yTitle": "Events / GeV",
                                    "xRange": [0., 200.],
                                    #"rebin": 5,
                                    "logy": False},
          "MHc-160_MA-15/ACand/eta": {"xTitle": "#eta(A)",
                                     "yTitle": "Events",
                                     "xRange": [-5., 5.],
                                     #"rebin": 5,
                                     "logy": False},
          "MHc-160_MA-15/ACand/phi": {"xTitle": "#phi(A)",
                                     "yTitle": "Events",
                                     "xRange": [-3.2, 3.2],
                                     #"rebin": 5,
                                     "logy": False},
          "MHc-160_MA-15/ACand/mass": {"xTitle": "M(A)",
                                     "yTitle": "Events / GeV",
                                     "xRange": [0., 200.],
                                     #"rebin": 5,
                                     "logy": False},
          "MHc-160_MA-15/score_TTFake": {"xTitle": "score(vsfake)",
                                              "yTitle": "Events",
                                              "xRange": [0., 1.],
                                              "rebin": 2,
                                              "logy": False},
          "MHc-160_MA-15/score_TTX": {"xTitle": "score(vsTTX)",
                                           "yTitle": "Events",
                                           "xRange": [0., 1.],
                                           "rebin": 2,
                                           "logy": False},
          "MHc-160_MA-85/ACand/pt": {"xTitle": "p_{T}(A)",
                                    "yTitle": "Events / GeV",
                                    "xRange": [0., 200.],
                                    #"rebin": 5,
                                    "logy": False},
          "MHc-160_MA-85/ACand/eta": {"xTitle": "#eta(A)",
                                     "yTitle": "Events",
                                     "xRange": [-5., 5.],
                                     #"rebin": 5,
                                     "logy": False},
          "MHc-160_MA-85/ACand/phi": {"xTitle": "#phi(A)",
                                     "yTitle": "Events",
                                     "xRange": [-3.2, 3.2],
                                     #"rebin": 5,
                                     "logy": False},
          "MHc-160_MA-85/ACand/mass": {"xTitle": "M(A)",
                                     "yTitle": "Events / GeV",
                                     "xRange": [0., 200.],
                                     #"rebin": 5,
                                     "logy": False},
          "MHc-160_MA-85/score_TTFake": {"xTitle": "score(vsfake)",
                                              "yTitle": "Events",
                                              "xRange": [0., 1.],
                                              "rebin": 2,
                                              "logy": False},
          "MHc-160_MA-85/score_TTX": {"xTitle": "score(vsTTX)",
                                           "yTitle": "Events",
                                           "xRange": [0., 1.],
                                           "rebin": 2,
                                           "logy": False},
          "MHc-160_MA-120/ACand/pt": {"xTitle": "p_{T}(A)",
                                    "yTitle": "Events / GeV",
                                    "xRange": [0., 200.],
                                    #"rebin": 5,
                                    "logy": False},
          "MHc-160_MA-120/ACand/eta": {"xTitle": "#eta(A)",
                                     "yTitle": "Events",
                                     "xRange": [-5., 5.],
                                     #"rebin": 5,
                                     "logy": False},
          "MHc-160_MA-120/ACand/phi": {"xTitle": "#phi(A)",
                                     "yTitle": "Events",
                                     "xRange": [-3.2, 3.2],
                                     #"rebin": 5,
                                     "logy": False},
          "MHc-160_MA-120/ACand/mass": {"xTitle": "M(A)",
                                     "yTitle": "Events / GeV",
                                     "xRange": [0., 200.],
                                     #"rebin": 5,
                                     "logy": False},
          "MHc-160_MA-120/score_TTFake": {"xTitle": "score(vsfake)",
                                              "yTitle": "Events",
                                              "xRange": [0., 1.],
                                              "rebin": 2,
                                              "logy": False},
          "MHc-160_MA-120/score_TTX": {"xTitle": "score(vsTTX)",
                                           "yTitle": "Events",
                                           "xRange": [0., 1.],
                                           "rebin": 2,
                                           "logy": False},
          "MHc-160_MA-15/ACand/pt": {"xTitle": "p_{T}(A)",
                                    "yTitle": "Events / GeV",
                                    "xRange": [0., 200.],
                                    #"rebin": 5,
                                    "logy": False},
          "MHc-160_MA-155/ACand/eta": {"xTitle": "#eta(A)",
                                     "yTitle": "Events",
                                     "xRange": [-5., 5.],
                                     #"rebin": 5,
                                     "logy": False},
          "MHc-160_MA-155/ACand/phi": {"xTitle": "#phi(A)",
                                     "yTitle": "Events",
                                     "xRange": [-3.2, 3.2],
                                     #"rebin": 5,
                                     "logy": False},
          "MHc-160_MA-155/ACand/mass": {"xTitle": "M(A)",
                                     "yTitle": "Events / GeV",
                                     "xRange": [0., 200.],
                                     #"rebin": 5,
                                     "logy": False},
          "MHc-160_MA-155/score_TTFake": {"xTitle": "score(vsfake)",
                                              "yTitle": "Events",
                                              "xRange": [0., 1.],
                                              "rebin": 2,
                                              "logy": False},
          "MHc-160_MA-155/score_TTX": {"xTitle": "score(vsTTX)",
                                           "yTitle": "Events",
                                           "xRange": [0., 1.],
                                           "rebin": 2,
                                           "logy": False},
          }

