histConfigs = {
    # base distributions
    "muons/1/pt":  {"xTitle": "p_{T}(#mu1)",
                    "yTitle": "Events / 10 GeV",
                    "xRange": [0., 300.],
                    "rebin": 10,
                    "logy": False},
    "muons/2/pt":  {"xTitle": "p_{T}(#mu2)",
                    "yTitle": "Events / 10 GeV",
                    "xRange": [0., 200.],
                    "rebin": 10,
                    "logy": False},
    "muons/3/pt":  {"xTitle": "p_{T}(#mu3)",
                    "yTitle": "Events / 10 GeV",
                    "xRange": [0., 200.],
                    "rebin": 10,
                    "logy": False},
    "muons/1/eta": {"xTitle": "#eta(#mu1)",
                    "yTitle": "Events",
                    "xRange": [-2.4, 2.4],
                    #"rebin": 10,
                    "logy": False},
    "muons/2/eta": {"xTitle": "#eta(#mu2)",
                    "yTitle": "Events",
                    "xRange": [-2.4, 2.4],
                    #"rebin": 10,
                    "logy": False},
    "muons/3/eta": {"xTitle": "#eta(#mu3)",
                    "yTitle": "Events",
                    "xRange": [-2.4, 2.4],
                    #"rebin": 10,
                    "logy": False},
    "muons/1/phi": {"xTitle": "#phi(#mu1)",
                    "yTitle": "Events",
                    "xRange": [-3.2, 3.2],
                    #"rebin": 10,
                    "logy": False},
    "muons/2/phi": {"xTitle": "#phi(#mu2)",
                    "yTitle": "Events",
                    "xRange": [-3.2, 3.2],
                    #"rebin": 10,
                    "logy": False},
    "muons/3/phi": {"xTitle": "#phi(#mu3)",
                    "yTitle": "Events",
                    "xRange": [-3.2, 3.2],
                    #"rebin": 10,
                    "logy": False},
    "electrons/1/pt":  {"xTitle": "p_{T}(e)",
                        "yTitle": "Events / 10 GeV",
                        "xRange": [0., 300.],
                        "rebin": 10,
                        "logy": False},
    "electrons/1/eta": {"xTitle": "#eta(e)",
                        "yTitle": "Events",
                        "xRange": [-2.5, 2.5],
                        #"rebin": 10,
                        "logy": False},
    "electrons/1/Phi": {"xTitle": "#phi(e)",
                        "yTitle": "Events",
                        "xRange": [-3.2, 3.2],
                        #"rebin": 10,
                        "logy": False},
    "jets/1/pt":   {"xTitle": "p_{T}(j1)",
                    "yTitle": "Events / 10 GeV",
                    "xRange": [0., 300.],
                    "rebin": 10,
                    "logy": False},
    "jets/2/pt":   {"xTitle": "p_{T}(j2)",
                    "yTitle": "Events / 10 GeV",
                    "xRange": [0., 300.],
                    "rebin": 10,
                    "logy": False},
    "jets/3/pt":   {"xTitle": "p_{T}(j3)",
                    "yTitle": "Events / 10 GeV",
                    "xRange": [0., 300.],
                    "rebin": 10,
                    "logy": False},
    "jets/4/pt":   {"xTitle": "p_{T}(j4)",
                    "yTitle": "Events / 10 GeV",
                    "xRange": [0., 300.],
                    "rebin": 10,
                    "logy": False},
    "jets/5/pt":   {"xTitle": "p_{T}(j5)",
                    "yTitle": "Events / 10 GeV",
                    "xRange": [0., 300.],
                    "rebin": 10,
                    "logy": False},
    "jets/1/eta":  {"xTitle": "#eta(j1)",
                    "yTitle": "Events",
                    "xRange": [-2.4, 2.4],
                    #"rebin": 10,
                    "logy": False},
    "jets/2/eta":  {"xTitle": "#eta(j2)",
                    "yTitle": "Events",
                    "xRange": [-2.4, 2.4],
                    #"rebin": 10,
                    "logy": False},
    "jets/3/eta":  {"xTitle": "#eta(j3)",
                    "yTitle": "Events",
                    "xRange": [-2.4, 2.4],
                    #"rebin": 10,
                    "logy": False},
    "jets/4/eta":  {"xTitle": "#eta(j4)",
                    "yTitle": "Events",
                    "xRange": [-2.4, 2.4],
                    #"rebin": 10,
                    "logy": False},
    "jets/5/eta":  {"xTitle": "#eta(j5)",
                    "yTitle": "Events",
                    "xRange": [-2.4, 2.4],
                    #"rebin": 10,
                    "logy": False},
    "jets/1/phi":  {"xTitle": "#phi(j1)",
                    "yTitle": "Events",
                    "xRange": [-3.2, 3.2],
                    #"rebin": 10,
                    "logy": False},
    "jets/2/phi":  {"xTitle": "#phi(j2)",
                    "yTitle": "Events",
                    "xRange": [-3.2, 3.2],
                    #"rebin": 10,
                    "logy": False},
    "jets/3/phi":  {"xTitle": "#phi(j3)",
                    "yTitle": "Events",
                    "xRange": [-3.2, 3.2],
                    #"rebin": 10,
                    "logy": False},
    "jets/4/phi":  {"xTitle": "#phi(j4)",
                    "yTitle": "Events",
                    "xRange": [-3.2, 3.2],
                    #"rebin": 10,
                    "logy": False},
    "jets/5/phi":  {"xTitle": "#phi(j5)",
                    "yTitle": "Events",
                    "xRange": [-3.2, 3.2],
                    #"rebin": 10,
                    "logy": False},
    "jets/1/mass": {"xTitle": "M(j1)",
                    "yTitle": "Events / 10 GeV",
                    "xRange": [0., 300.],
                    "rebin": 10,
                    "logy": False},
    "jets/2/mass": {"xTitle": "M(j2)",
                    "yTitle": "Events / 10 GeV",
                    "xRange": [0., 300.],
                    "rebin": 10,
                    "logy": False},
    "jets/3/mass": {"xTitle": "M(j3)",
                    "yTitle": "Events / 10 GeV",
                    "xRange": [0., 300.],
                    "rebin": 10,
                    "logy": False},
    "jets/4/mass": {"xTitle": "M(j4)",
                    "yTitle": "Events / 10 GeV",
                    "xRange": [0., 300.],
                    "rebin": 10,
                    "logy": False},
    "jets/5/mass": {"xTitle": "M(j5)",
                    "yTitle": "Events / 10 GeV",
                    "xRange": [0., 300.],
                    "rebin": 10,
                    "logy": False},
    "jets/1/charge":   {"xTitle": "charge(j1)",
                        "yTitle": "Events",
                        "xRange": [-1., 1.],
                        #"rebin": 10, 
                        "logy": False},
    "jets/2/charge":   {"xTitle": "charge(j2)",
                        "yTitle": "Events",
                        "xRange": [-1., 1.],
                        #"rebin": 10, 
                        "logy": False},
    "jets/3/charge":   {"xTitle": "charge(j3)",
                        "yTitle": "Events",
                        "xRange": [-1., 1.],
                        #"rebin": 10, 
                        "logy": False},
    "jets/4/charge":   {"xTitle": "charge(j4)",
                        "yTitle": "Events",
                        "xRange": [-1., 1.],
                        #"rebin": 10, 
                        "logy": False},
    "jets/5/charge":   {"xTitle": "charge(j5)",
                        "yTitle": "Events",
                        "xRange": [-1., 1.],
                        #"rebin": 10, 
                        "logy": False},
    "jets/size":   {"xTitle": "N_{j}",
                    "yTitle": "Events",
                    "xRange": [0, 10],
                    "logy": False},
    "bjets/1/pt": {"xTitle": "p_{T}(b1)",
                    "yTitle": "Events / 10 GeV",
                    "xRange": [0., 300.],
                    "rebin": 10,
                    "logy": False},
    "bjets/2/pt":  {"xTitle": "p_{T}(b2)",
                    "yTitle": "Events / 10 GeV",
                    "xRange": [0., 300.],
                    "rebin": 10,
                    "logy": False},
    "bjets/3/pt":  {"xTitle": "p_{T}(b3)",
                    "yTitle": "Events / 10 GeV",
                    "xRange": [0., 300.],
                    "rebin": 10,
                    "logy": False},
    "bjets/1/eta": {"xTitle": "#eta(b1)",
                    "yTitle": "Events",
                    "xRange": [-2.4, 2.4],
                    #"rebin": 10,
                    "logy": False},
    "bjets/2/eta": {"xTitle": "#eta(b2)",
                    "yTitle": "Events",
                    "xRange": [-2.4, 2.4],
                    #"rebin": 10,
                    "logy": False},
    "bjets/3/eta": {"xTitle": "#eta(b3)",
                    "yTitle": "Events",
                    "xRange": [-2.4, 2.4],
                    #"rebin": 10,
                    "logy": False},
    "bjets/1/phi": {"xTitle": "#phi(b1)",
                    "yTitle": "Events",
                    "xRange": [-3.2, 3.2],
                    #"rebin": 10,
                    "logy": False},
    "bjets/2/phi": {"xTitle": "#phi(b2)",
                    "yTitle": "Events",
                    "xRange": [-3.2, 3.2],
                    #"rebin": 10,
                    "logy": False},
    "bjets/3/phi": {"xTitle": "#phi(b3)",
                    "yTitle": "Events",
                    "xRange": [-3.2, 3.2],
                    #"rebin": 10,
                    "logy": False},
    "bjets/1/mass":    {"xTitle": "M(b1)",
                        "yTitle": "Events / 10 GeV",
                        "xRange": [0., 300.],
                        "rebin": 10,
                        "logy": False},
    "bjets/2/mass":    {"xTitle": "M(b2)",
                        "yTitle": "Events / 10 GeV",
                        "xRange": [0., 300.],
                        "rebin": 10,
                        "logy": False},
    "bjets/3/mass":    {"xTitle": "M(b3)",
                        "yTitle": "Events / 10 GeV",
                        "xRange": [0., 300.],
                        "rebin": 10,
                        "logy": False},
    "bjets/1/charge":  {"xTitle": "charge(b1)",
                        "yTitle": "Events",
                        "xRange": [-1., 1.],
                        #"rebin": 10, 
                        "logy": False},
    "bjets/2/charge":  {"xTitle": "charge(b2)",
                        "yTitle": "Events",
                        "xRange": [-1., 1.],
                        #"rebin": 10, 
                        "logy": False},
    "bjets/3/charge":  {"xTitle": "charge(b3)",
                        "yTitle": "Events",
                        "xRange": [-1., 1.],
                        #"rebin": 10, 
                        "logy": False},
    "bjets/size":  {"xTitle": "N_{b}",
                    "yTitle": "Events",
                    "xRange": [0, 10],
                    "logy": False},
    "METv/pt": {"xTitle": "E_{T}^{miss}",
                "yTitle": "Events / 10 GeV",
                "xRange": [0., 300.],
                "rebin": 10,
                "logy": False},
    "METv/phi":    {"xTitle": "#phi(#vec{p_{T}}^{miss}})",
                    "yTitle": "Events",
                    "xRange": [-3.2, 3.2],
                    #"rebin": 10,
                    "logy": False},
    "stack/pt":    {"xTitle": "p_{T}(pairs)",
                    "yTitle": "N_{pairs}",
                    "xRange": [0., 300.],
                    "rebin": 10,
                    "logy": False},
    "stack/eta":   {"xTitle": "#eta(pairs)",
                    "yTitle": "N_{pairs}",
                    "xRange": [-5., 5.],
                    #"rebin": 5,
                    "logy": False},
    "stack/phi":   {"xTitle": "#phi(pairs)",
                    "yTitle": "N_{pairs}",
                    "xRange": [-3.2, 3.2],
                    #"rebin": 10,
                    "logy": False},
    "stack/mass":  {"xTitle": "M(pairs)",
                    "yTitle": "N_{pairs}",
                    "xRange": [0., 199.],
                    #"rebin": 10,
                    "logy": False},
    "ZCand/mass":  {"xTitle": "M(Z)",
                    "yTitle": "Events / GeV",
                    "xRange": [75, 105],
                    "logy": False},
    "ZCand/eta":   {"xTitle": "#eta(Z)",
                    "yTitle": "Events",
                    "xRange": [-5., 5.],
                    "rebin": 5,
                    "logy": False},
    "nZCand/mass": {"xTitle": "M(nZ)",
                    "yTitle": "Events / GeV",
                    "xRange": [0, 300],
                    "logy": False},
    "nZCand/eta":   {"xTitle": "#eta(Zn)",
                    "yTitle": "Events",
                    "xRange": [-5., 5.],
                    "rebin": 5,
                    "logy": False},
    "MHc-70_MA-65/score_nonprompt": {
        "xTitle": "score(vs. nonprompt)",
        "yTitle": "Events",
        "xRange": [0., 1.],
        #"rebin": 10,
        "logy": True},
    "MHc-70_MA-65/score_diboson": {
        "xTitle": "score(vs. diboson)",
        "yTitle": "Events",
        "xRange": [0., 1.],
        #"rebin": 10,
        "logy": True},
    "MHc-70_MA-65/score_ttZ": {
        "xTitle": "score(vs. ttZ)",
        "yTitle": "Events",
        "xRange": [0., 1.],
        #"rebin": 10,
        "logy": True},
    "MHc-100_MA-95/score_nonprompt": {
        "xTitle": "score(vs. nonprompt)",
        "yTitle": "Events",
        "xRange": [0., 1.],
        #"rebin": 10,
        "logy": True},
    "MHc-100_MA-95/score_diboson": {
        "xTitle": "score(vs. diboson)",
        "yTitle": "Events",
        "xRange": [0., 1.],
        #"rebin": 10,
        "logy": True},
    "MHc-100_MA-95/score_ttZ": {
        "xTitle": "score(vs. ttZ)",
        "yTitle": "Events",
        "xRange": [0., 1.],
        #"rebin": 10,
        "logy": True},
    "MHc-130_MA-90/score_nonprompt": {
        "xTitle": "score(vs. nonprompt)",
        "yTitle": "Events",
        "xRange": [0., 1.],
        #"rebin": 10,
        "logy": True},
    "MHc-130_MA-90/score_diboson": {
        "xTitle": "score(vs. diboson)",
        "yTitle": "Events",
        "xRange": [0., 1.],
        #"rebin": 10,
        "logy": True},
    "MHc-130_MA-90/score_ttZ": {
        "xTitle": "score(vs. ttZ)",
        "yTitle": "Events",
        "xRange": [0., 1.],
        #"rebin": 10,
        "logy": True},
    "MHc-160_MA-85/score_nonprompt": {
        "xTitle": "score(vs. nonprompt)",
        "yTitle": "Events",
        "xRange": [0., 1.],
        #"rebin": 10,
        "logy": True},
    "MHc-160_MA-85/score_diboson": {
        "xTitle": "score(vs. diboson)",
        "yTitle": "Events",
        "xRange": [0., 1.],
        #"rebin": 10,
        "logy": True},
    "MHc-160_MA-85/score_ttZ": {
        "xTitle": "score(vs. ttZ)",
        "yTitle": "Events",
        "xRange": [0., 1.],
        #"rebin": 10,
        "logy": True},
    "MHc-160_MA-120/score_nonprompt": {
        "xTitle": "score(vs. nonprompt)",
        "yTitle": "Events",
        "xRange": [0., 1.],
        #"rebin": 10,
        "logy": True},
    "MHc-160_MA-120/score_diboson": {
        "xTitle": "score(vs. diboson)",
        "yTitle": "Events",
        "xRange": [0., 1.],
        #"rebin": 10,
        "logy": True},
    "MHc-160_MA-120/score_ttZ": {
        "xTitle": "score(vs. ttZ)",
        "yTitle": "Events",
        "xRange": [0., 1.],
        #"rebin": 10,
        "logy": True}
}
